version: 2
updates:
  - package-ecosystem: 'github-actions'
    directory: '/'
    schedule:
      interval: 'monthly'
    groups:
      docker:
        patterns:
          - 'docker/*'

  - package-ecosystem: 'docker'
    directory: '/'
    schedule:
      interval: 'daily'
